[project]
name = "ai-powered-data-quality-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "crewai[tools]>=0.152.0",
    "google-generativeai>=0.8.5",
]
